// <auto-generated />
using System;
using System.Collections.Generic;
using Dwellers.Common.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dwellers.Common.Infrastructure.Migrations
{
    [DbContext(typeof(DwellerDbContext))]
    [Migration("20240508113418_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dweller_schema")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dwellers.Bulletins.Domain.Bulletins.Bulletin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DwellerId")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IsCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IsModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PriorityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DwellerId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("StatusId");

                    b.ToTable("Bulletins", "dweller_schema");
                });

            modelBuilder.Entity("Dwellers.Bulletins.Domain.Bulletins.BulletinPriority", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BulletinPriorities", "dweller_schema");
                });

            modelBuilder.Entity("Dwellers.Bulletins.Domain.Bulletins.BulletinScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BulletinId")
                        .HasColumnType("uuid");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BulletinId")
                        .IsUnique();

                    b.ToTable("BulletinScopes", "dweller_schema");
                });

            modelBuilder.Entity("Dwellers.Bulletins.Domain.Bulletins.BulletinStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BulletinStatus", "dweller_schema");
                });

            modelBuilder.Entity("Dwellers.Bulletins.Domain.Bulletins.BulletinTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BulletinId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BulletinId");

                    b.ToTable("BulletinTags", "dweller_schema");
                });

            modelBuilder.Entity("Dwellers.Bulletins.Domain.Bulletins.ScopedDwelling", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BulletinId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BulletinScopeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DwellingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BulletinId");

                    b.HasIndex("BulletinScopeId");

                    b.HasIndex("DwellingId");

                    b.ToTable("ScopedDwellings", "dweller_schema");
                });

            modelBuilder.Entity("Dwellers.Chat.Domain.Entities.DwellerConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IsCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IsModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DwellerConversations", "dweller_schema");
                });

            modelBuilder.Entity("Dwellers.Chat.Domain.Entities.DwellerMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DwellerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("IsModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("DwellerId");

                    b.ToTable("DwellerMessages", "dweller_schema");
                });

            modelBuilder.Entity("Dwellers.Chat.Domain.Entities.MemberInConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DwellingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("IsCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IsModified")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("DwellingId");

                    b.ToTable("MemberInConversations", "dweller_schema");
                });

            modelBuilder.Entity("Dwellers.DwellerCore.Domain.Entities.Dwellers.Dweller", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IsCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IsModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("ProfilePhoto")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("Dwellers", "dweller_schema");
                });

            modelBuilder.Entity("Dwellers.DwellerCore.Domain.Entities.DwellingInhabitant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DwellerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DwellingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DwellerId")
                        .IsUnique();

                    b.HasIndex("DwellingId")
                        .IsUnique();

                    b.ToTable("DwellingInhabitants", "dweller_schema");
                });

            modelBuilder.Entity("Dwellers.DwellerCore.Domain.Entities.Dwellings.Dwelling", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<List<Guid>>("DwellingFriends")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<byte[]>("DwellingProfilePhoto")
                        .HasColumnType("bytea");

                    b.Property<Guid>("InvitationCode")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IsCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IsModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dwellings", "dweller_schema");
                });

            modelBuilder.Entity("Dwellers.DwellerCore.Domain.Entities.Dwellings.DwellingGallery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DwellingId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("DwellingImage")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("DwellingId");

                    b.ToTable("DwellingGallery", "dweller_schema");
                });

            modelBuilder.Entity("Dwellers.DwellersEvents.Domain.Entites.DwellerEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DwellerId")
                        .HasColumnType("text");

                    b.Property<Guid>("DwellingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EventScopeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IsCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IsModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DwellerId");

                    b.HasIndex("DwellingId");

                    b.HasIndex("EventScopeId");

                    b.ToTable("DwellerEvents", "dweller_schema");
                });

            modelBuilder.Entity("Dwellers.DwellersEvents.Domain.Entites.ValueObjects.DwellerScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DwellerScopes", "dweller_schema");
                });

            modelBuilder.Entity("Dwellers.Offerings.Domain.DwellerItems.BorrowedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DwellerItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DwellingId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IsCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IsReturned")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DwellerItemId");

                    b.HasIndex("DwellingId");

                    b.ToTable("BorrowedItems", "dweller_schema");
                });

            modelBuilder.Entity("Dwellers.Offerings.Domain.DwellerItems.DwellerItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBorrowed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IsCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IsModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("ItemPhoto")
                        .HasColumnType("bytea");

                    b.Property<int>("ItemScope")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerOfItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerOfItemId");

                    b.ToTable("DwellerItems", "dweller_schema");
                });

            modelBuilder.Entity("Dwellers.Offerings.Domain.DwellerServices.DwellerService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IsCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IsModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ServiceScope")
                        .HasColumnType("integer");

                    b.Property<bool>("ServiceStatus")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("DwellerServices", "dweller_schema");
                });

            modelBuilder.Entity("Dwellers.Offerings.Domain.DwellerServices.ProvidedService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<Guid>("DwellerServiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DwellingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("IsCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IsModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsProvider")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("ServiceReturned")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DwellerServiceId");

                    b.HasIndex("DwellingId");

                    b.ToTable("ProvidedServices", "dweller_schema");
                });

            modelBuilder.Entity("Dwellers.Bulletins.Domain.Bulletins.Bulletin", b =>
                {
                    b.HasOne("Dwellers.DwellerCore.Domain.Entities.Dwellers.Dweller", "Dweller")
                        .WithMany()
                        .HasForeignKey("DwellerId");

                    b.HasOne("Dwellers.Bulletins.Domain.Bulletins.BulletinPriority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dwellers.Bulletins.Domain.Bulletins.BulletinStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dweller");

                    b.Navigation("Priority");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Dwellers.Bulletins.Domain.Bulletins.BulletinScope", b =>
                {
                    b.HasOne("Dwellers.Bulletins.Domain.Bulletins.Bulletin", "Bulletin")
                        .WithOne("Scope")
                        .HasForeignKey("Dwellers.Bulletins.Domain.Bulletins.BulletinScope", "BulletinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bulletin");
                });

            modelBuilder.Entity("Dwellers.Bulletins.Domain.Bulletins.BulletinTag", b =>
                {
                    b.HasOne("Dwellers.Bulletins.Domain.Bulletins.Bulletin", "Bulletin")
                        .WithMany("Tags")
                        .HasForeignKey("BulletinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bulletin");
                });

            modelBuilder.Entity("Dwellers.Bulletins.Domain.Bulletins.ScopedDwelling", b =>
                {
                    b.HasOne("Dwellers.Bulletins.Domain.Bulletins.Bulletin", "Bulletin")
                        .WithMany()
                        .HasForeignKey("BulletinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dwellers.Bulletins.Domain.Bulletins.BulletinScope", null)
                        .WithMany("DwellingsInScope")
                        .HasForeignKey("BulletinScopeId");

                    b.HasOne("Dwellers.DwellerCore.Domain.Entities.Dwellings.Dwelling", "Dwelling")
                        .WithMany()
                        .HasForeignKey("DwellingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bulletin");

                    b.Navigation("Dwelling");
                });

            modelBuilder.Entity("Dwellers.Chat.Domain.Entities.DwellerMessage", b =>
                {
                    b.HasOne("Dwellers.Chat.Domain.Entities.DwellerConversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dwellers.DwellerCore.Domain.Entities.Dwellers.Dweller", "Dweller")
                        .WithMany()
                        .HasForeignKey("DwellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Dweller");
                });

            modelBuilder.Entity("Dwellers.Chat.Domain.Entities.MemberInConversation", b =>
                {
                    b.HasOne("Dwellers.Chat.Domain.Entities.DwellerConversation", "Conversation")
                        .WithMany("MemberInConversation")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dwellers.DwellerCore.Domain.Entities.Dwellings.Dwelling", "Dwelling")
                        .WithMany()
                        .HasForeignKey("DwellingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Dwelling");
                });

            modelBuilder.Entity("Dwellers.DwellerCore.Domain.Entities.DwellingInhabitant", b =>
                {
                    b.HasOne("Dwellers.DwellerCore.Domain.Entities.Dwellers.Dweller", "Dweller")
                        .WithOne("DwellingInhabitant")
                        .HasForeignKey("Dwellers.DwellerCore.Domain.Entities.DwellingInhabitant", "DwellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dwellers.DwellerCore.Domain.Entities.Dwellings.Dwelling", "Dwelling")
                        .WithOne("DwellingInhabitant")
                        .HasForeignKey("Dwellers.DwellerCore.Domain.Entities.DwellingInhabitant", "DwellingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dweller");

                    b.Navigation("Dwelling");
                });

            modelBuilder.Entity("Dwellers.DwellerCore.Domain.Entities.Dwellings.DwellingGallery", b =>
                {
                    b.HasOne("Dwellers.DwellerCore.Domain.Entities.Dwellings.Dwelling", "Dwelling")
                        .WithMany("DwellingGallery")
                        .HasForeignKey("DwellingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dwelling");
                });

            modelBuilder.Entity("Dwellers.DwellersEvents.Domain.Entites.DwellerEvent", b =>
                {
                    b.HasOne("Dwellers.DwellerCore.Domain.Entities.Dwellers.Dweller", "Dweller")
                        .WithMany()
                        .HasForeignKey("DwellerId");

                    b.HasOne("Dwellers.DwellerCore.Domain.Entities.Dwellings.Dwelling", "Dwelling")
                        .WithMany()
                        .HasForeignKey("DwellingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dwellers.DwellersEvents.Domain.Entites.ValueObjects.DwellerScope", "EventScope")
                        .WithMany()
                        .HasForeignKey("EventScopeId");

                    b.Navigation("Dweller");

                    b.Navigation("Dwelling");

                    b.Navigation("EventScope");
                });

            modelBuilder.Entity("Dwellers.Offerings.Domain.DwellerItems.BorrowedItem", b =>
                {
                    b.HasOne("Dwellers.Offerings.Domain.DwellerItems.DwellerItem", "DwellerItem")
                        .WithMany("BorrowedItems")
                        .HasForeignKey("DwellerItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dwellers.DwellerCore.Domain.Entities.Dwellings.Dwelling", "Dwelling")
                        .WithMany()
                        .HasForeignKey("DwellingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DwellerItem");

                    b.Navigation("Dwelling");
                });

            modelBuilder.Entity("Dwellers.Offerings.Domain.DwellerItems.DwellerItem", b =>
                {
                    b.HasOne("Dwellers.DwellerCore.Domain.Entities.Dwellings.Dwelling", "OwnerOfItem")
                        .WithMany()
                        .HasForeignKey("OwnerOfItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerOfItem");
                });

            modelBuilder.Entity("Dwellers.Offerings.Domain.DwellerServices.ProvidedService", b =>
                {
                    b.HasOne("Dwellers.Offerings.Domain.DwellerServices.DwellerService", "DwellerService")
                        .WithMany("ProvidedServices")
                        .HasForeignKey("DwellerServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dwellers.DwellerCore.Domain.Entities.Dwellings.Dwelling", "Dwelling")
                        .WithMany()
                        .HasForeignKey("DwellingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DwellerService");

                    b.Navigation("Dwelling");
                });

            modelBuilder.Entity("Dwellers.Bulletins.Domain.Bulletins.Bulletin", b =>
                {
                    b.Navigation("Scope")
                        .IsRequired();

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Dwellers.Bulletins.Domain.Bulletins.BulletinScope", b =>
                {
                    b.Navigation("DwellingsInScope");
                });

            modelBuilder.Entity("Dwellers.Chat.Domain.Entities.DwellerConversation", b =>
                {
                    b.Navigation("MemberInConversation");
                });

            modelBuilder.Entity("Dwellers.DwellerCore.Domain.Entities.Dwellers.Dweller", b =>
                {
                    b.Navigation("DwellingInhabitant")
                        .IsRequired();
                });

            modelBuilder.Entity("Dwellers.DwellerCore.Domain.Entities.Dwellings.Dwelling", b =>
                {
                    b.Navigation("DwellingGallery");

                    b.Navigation("DwellingInhabitant")
                        .IsRequired();
                });

            modelBuilder.Entity("Dwellers.Offerings.Domain.DwellerItems.DwellerItem", b =>
                {
                    b.Navigation("BorrowedItems");
                });

            modelBuilder.Entity("Dwellers.Offerings.Domain.DwellerServices.DwellerService", b =>
                {
                    b.Navigation("ProvidedServices");
                });
#pragma warning restore 612, 618
        }
    }
}
